/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author mapam
 */
public class VentanaInicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicioSesion
     */
    public VentanaInicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CajonUsuario = new javax.swing.JTextField();
        CajonContrasena = new javax.swing.JPasswordField();
        botonIniciarSesion = new javax.swing.JLabel();
        FondoInicioSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 333));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 333));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CajonUsuario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        CajonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajonUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(CajonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 180, 20));

        CajonContrasena.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(CajonContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 180, 20));

        botonIniciarSesion.setBackground(new java.awt.Color(18, 146, 195));
        botonIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        botonIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonIniciarSesion.setText("Iniciar sesión");
        botonIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonIniciarSesion.setOpaque(true);
        getContentPane().add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 120, 30));

        FondoInicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.png"))); // NOI18N
        getContentPane().add(FondoInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 333));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CajonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajonUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajonUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CajonContrasena;
    private javax.swing.JTextField CajonUsuario;
    private javax.swing.JLabel FondoInicioSesion;
    private javax.swing.JLabel botonIniciarSesion;
    // End of variables declaration//GEN-END:variables
}
